name: Common
on:
  workflow_call:
    inputs:
      type:
        required: true
        type: string
      is-snapshot:
        required: false
        type: boolean
        default: true
      change-log:
        required: false
        type: string

jobs:
  build-common:
    name: Build Common
    runs-on: ubuntu-latest
    environment: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'
          cache: 'gradle'
          
      - name: Build
        env:
          IS_SNAPSHOT: ${{ inputs.is-snapshot }}
        run: |
          ./gradlew clean shadowJar --info --stacktrace
          
      - name: Collect build artifacts
        run: |
          mkdir -p release-artifacts
          # 复制所有构建的JAR文件到release-artifacts目录
          find . -name "*.jar" -path "*/build/libs/*" ! -name "*-sources.jar" ! -name "*-javadoc.jar" -exec cp {} release-artifacts/ \;
          echo "已收集的 JAR 文件:"
          ls -la release-artifacts/
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: release-artifacts/*.jar
          retention-days: 1
          
      - name: Publish to Modrinth
        if: ${{ !inputs.is-snapshot && inputs.change-log != '' }}
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CHANGE_LOG: ${{ inputs.change-log }}
        run: |
          ./gradlew modrinth --info --stacktrace
