name: Release
on:
  release:
    types: [published]

jobs:
  build-release:
    name: Build Release
    uses: ./.github/workflows/common.yml
    with:
      type: Release
      is-snapshot: false
      change-log: ${{ github.event.release.body }}
    secrets: inherit

  upload-to-release:
    name: Upload to GitHub Release
    needs: build-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: release-artifacts
          
      - name: List downloaded artifacts
        run: |
          echo "Downloaded artifacts:"
          ls -la release-artifacts/
          
      - name: Extract version from tag
        id: get_version
        run: |
          # 从发布标签中提取版本号
          VERSION="${{ github.event.release.tag_name }}"
          # 如果标签以 'v' 开头，去掉它
          if [[ $VERSION == v* ]]; then
            VERSION=${VERSION#v}
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Extracted version: $VERSION"
          
      - name: Rename artifact for release
        run: |
          # 找到下载的 JAR 文件
          JAR_FILE=$(find release-artifacts -name "*.jar" | head -1)
          if [ -z "$JAR_FILE" ]; then
            echo "Error: No JAR file found in artifacts!"
            exit 1
          fi
          
          # 重命名为版本号
          cp "$JAR_FILE" "I18nUpdateMod-$VERSION.jar"
          echo "Renamed to: I18nUpdateMod-$VERSION.jar"
          
      - name: Upload to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./I18nUpdateMod-${{ env.VERSION }}.jar
          asset_name: I18nUpdateMod-${{ env.VERSION }}.jar
          asset_content_type: application/java-archive
